universe = vanilla

transfer_input_files = 📥 //declare the necessary inputs
executable = /cvmfs/virgo.ego-gw.it/⚙️ //path to executable
arguments = ⚙️ //executable args
transfer_output_files = 📤 //declare the outputs here

log = std.log
output = std.out
error = std.err

should_transfer_files = YES/NO //make your choice
when_to_transfer_output = ON_EXIT
transfer_executable = False //since already distributed

accounting_group = accounting_group_goes_here
accounting_group_user = albert.einstein

queue 1
